spark:
  app_name: "MovieRecommendationSystem"
  master: "local[*]"
  log_level: "WARN"
  configs:
    spark.sql.shuffle.partitions: 400
    spark.sql.adaptive.enabled: true
    spark.sql.adaptive.coalescePartitions.enabled: true
    spark.sql.adaptive.skewJoin.enabled: true
    spark.sql.adaptive.localShuffleReader.enabled: true
    spark.sql.autoBroadcastJoinThreshold: 104857600
    spark.driver.memory: "2g"
    spark.executor.memory: "2g"
    spark.executor.cores: 2
    spark.sql.session.timeZone: "UTC"
